version: "~> 1.0"
os: linux
dist: xenial
language: php
php:
  - 7.4
branches:
  only:
    - master
    - main
before_install:
  - openssl aes-256-cbc -K $encrypted_f9e1b166ba47_key -iv $encrypted_f9e1b166ba47_iv
    -in .travis/.env.travis.enc -out ./.env -d
  - openssl aes-256-cbc -K $encrypted_04c1f44da757_key -iv $encrypted_04c1f44da757_iv
    -in .travis/travis_ed.enc -out ~/.ssh/travis_ed -d
install:
  - composer install --no-progress --no-interaction --optimize-autoloader --no-dev
  - npm install
  - npm run production
  - php artisan config:clear
  - php artisan key:generate
  - php artisan storage:link
  - php artisan config:cache
  - php artisan route:cache
script:
  - skip
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis_ed
  - ssh-add ~/.ssh/travis_ed
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      repo: skyunlimitedinc/ays
      branch: master
