version: "3"

services:

  # HAProxy load balancer
  balancer:
    image: haproxy
    container_name: balancer
    restart: unless-stopped
    volumes:
      - "~/web/config/haproxy:/usr/local/etc/haproxy:ro"
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    depends_on:
      - ays

  # American Yacht Supply site (Apache & PHP services with Laravel)
  ays:
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: "sturmb/sky-ays:2020.10.2"
    container_name: ays
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - acsays-db
      - redis
    ports:
      - "8083:80"
      - "4545:443"
    networks:
      - web

  # MySQL Service for the ACS and AYS sites' databases
  acsays-db:
    image: mysql
    container_name: acsays-db
    restart: unless-stopped
    ports:
      - "3326:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
    volumes:
      - acsays-dbdata:/var/lib/mysql
    networks:
      - web

  # Redis Service
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - web

# Docker Networks
networks:
  web:
    driver: bridge
    name: web

# Volumes
volumes:
  acsays-dbdata:
    driver: local
    name: acsays-dbdata
  redis-data:
    driver: local
    name: redis-data
