version: "3"

services:

  # Laravel app (Apache & PHP services with Laravel)
  ays:
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: "sturmb/sky-ays:2020.final"
    container_name: ays
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: www-ays
      SERVICE_TAGS: dev
      VIRTUAL_HOST: ays,americanyachtsupply.com
      # VIRTUAL_PROTO: http
      # VIRTUAL_PORT: 80
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      CERT_NAME: skyunlimitedinc
    working_dir: /var/www/html
    expose:
      - "80"
      - "443"
