version: "3"

services:

  # HAProxy load balancer
  balancer:
    image: haproxy
    container_name: balancer
    restart: unless-stopped
    volumes:
      - ./docker-config/haproxy:/usr/local/etc/haproxy:ro
    networks:
      - web
    ports:
      - 8080:80
      - 4443:443
      - 1936:1936
    depends_on:
      - ays

  # Laravel app (Apache & PHP services with Laravel)
  ays:
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: "sturmb/sky-ays:2020.9.1"
    container_name: ays
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - acsays-db
    ports:
      - 8083:80
      - 4545:443
    networks:
      - web

  # MySQL Service
  acsays-db:
    image: mysql:5.7.29
    container_name: acsays-db
    restart: unless-stopped
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - web

# Docker Networks
networks:
  web:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
