name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
        run: |
          echo $ENV_PASSPHRASE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
